export const buttonsVariables = [
  {
    id: 'grey1',
    background: '--grey0',
    border: '--grey0',
    color: '--grey10',
    hover: { background: '--grey1', border: '--grey1', color: '--grey10' },
    focus: { background: '--grey1', border: '--grey1', color: '--grey10' },
  },
  {
    id: 'negative',
    background: '--grey6',
    border: '--grey6',
    color: '--grey2',
    hover: { background: '--grey5', border: '--grey5', color: '--grey2' },
    focus: { background: '--grey5', border: '--grey5', color: '--grey2' },
  },
  {
    id: 'disable',
    background: '--brand5',
    border: '--brand5',
    color: '--white',
    hover: { background: '--brand5', border: '--brand5', color: '--white' },
    focus: { background: '--brand5', border: '--brand5', color: '--white' },
  },
  {
    id: 'brand1',
    background: '--brand1',
    border: '--brand1',
    color: '--white',
    hover: { background: '--brand2', border: '--brand2', color: '--white' },
    focus: { background: '--brand4', border: '--brand4', color: '--brand1' },
  },
  {
    id: 'light',
    background: '--brand10',
    border: '--grey10',
    color: '--grey1',
    hover: {
      background: '--tranparente',
      border: '--grey10',
      color: '--gray10',
    },
    focus: {
      background: '--tranparente',
      border: '--grey10',
      color: '--gray10',
    },
  },
  {
    id: 'outlineLightHover',
    background: '--gray10',
    border: '--grey10',
    color: '--grey1',
    hover: { background: '--gray10', border: '--grey10', color: '--grey1' },
    focus: { background: '--gray10', border: '--grey10', color: '--grey1' },
  },
  {
    id: 'outline1',
    background: '--tranparente',
    border: '--grey0',
    color: '--grey0',
    hover: { background: '--tranparente', border: '--grey0', color: '--grey0' },
    focus: { background: '--tranparente', border: '--grey0', color: '--grey0' },
  },
  {
    id: 'big45',
    background: '--grey1',
    border: '--grey1',
    color: '--grey10',
    hover: { background: '--grey1', border: '--grey10', color: '--grey10' },
    focus: { background: '--grey1', border: '--grey10', color: '--grey10' },
  },
  {
    id: 'outline2',
    background: '--tranparente',
    border: '--grey4',
    color: '--grey0',
    hover: { background: '--grey0', border: '--grey0', color: '--grey10' },
    focus: { background: '--grey0', border: '--grey0', color: '--grey10' },
  },
  {
    id: 'outlineBrand1',
    background: '--tranparente',
    border: '--brand1',
    color: '--brand1',
    hover: { background: '--brand4', border: '--brand1', color: '--brand1' },
    focus: { background: '--brand4', border: '--brand1', color: '--brand1' },
  },
  {
    id: 'link',
    background: '--tranparente',
    border: '--tranparente',
    color: '--grey0',
    hover: { background: '--grey8', border: '--grey8', color: '--grey0' },
    focus: { background: '--grey8', border: '--grey8', color: '--grey0' },
  },
  {
    id: 'alert',
    background: '--alert3',
    border: '--alert3',
    color: '--alert1',
    hover: { background: '--alert2', border: '--alert2', color: '--alert1' },
    focus: { background: '--alert2', border: '--alert2', color: '--alert1' },
  },
  {
    id: 'sucess',
    background: '--sucess3',
    border: '--sucess3',
    color: '--sucess1',
    hover: { background: '--succes2', border: '--sucess2', color: '--sucess1' },
    focus: { background: '--succes2', border: '--sucess2', color: '--sucess1' },
  },
  {
    id: 'brandDisable',
    background: '--brand3',
    border: '--brand3',
    color: '--brand4',
    hover: { background: '--brand3', border: '--brand3', color: 'brand4' },
    focus: { background: '--brand3', border: '--brand3', color: 'brand4' },
  },
];
